ktor:
  environment: dev
  deployment:
    port: "$PORT:8080"
    watch:
      - classes
      - resources
    shutdown:
      url: "/shutdown"
#    sslPort: 8443
  application:
    modules:
      - br.com.joaovq.ApplicationKt.module
  h2:
    console:
      enabled: true
      path: /h2-console
#  security:
#    ssl:
#      keyStore: keystore.jks
#      keyAlias: sampleAlias
#      keyStorePassword: foobar
#      privateKeyPassword: foobar
  development: "$DEVELOPMENT:true"
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"
storage:
  driverClassName: org.h2.Driver
  jdbcURL: "jdbc:h2:file:"
  dbFilePath: build/db;DATABASE_TO_UPPER=false
  user: ""
  password: ""
  ehcacheFilePath: build/ehcache
