ktor:
  environment: dev
  deployment:
    port: "$PORT:8080"
    watch:
      - classes
      - resources
#    sslPort: 8443
  application:
    modules:
      - com.example.ApplicationKt.module
#  security:
#    ssl:
#      keyStore: keystore.jks
#      keyAlias: sampleAlias
#      keyStorePassword: foobar
#      privateKeyPassword: foobar
  development: "$DEVELOPMENT:true"
jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"