CREATE TABLE IF NOT EXISTS USER_TB (
    ID VARCHAR(255) PRIMARY KEY,
    USER_USERNAME VARCHAR(128) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL
)
ALTER TABLE USER_TB ADD CONSTRAINT USER_TB_USER_USERNAME_UNIQUE UNIQUE (USER_USERNAME)
